### ISSUE TITLE
How get jobs fetched from redis?

### ISSUE THREAD

**Issue by railsmechanic** [edgurgel/verk#1]
I'm a noob to Elixir and looking for a job queue that I can adapt to my needs and your project looks good.
After a quick look on your source, I'm wondering where new jobs gets fetched from Redis.
Is the fetching done via the 
```elixir
def handle_info(:timeout, state) do
```
function in the `Verk.WorkersManager` module?

Many thanks for explaining

**Comment by edgurgel** [comment]
That's exactly where it happens. If the GenServer didn't receive any message, a :timeout will happen (that's the optional last argument of a gen server reply/noreply, more info here: http://www.erlang.org/doc/man/gen_server.html) and the WorkersManager will look for jobs to execute.

https://github.com/edgurgel/verk/blob/master/lib/verk/workers_manager.ex#L64-L77

It asks the QueueManager for jobs. If there are jobs to run it will start them, if there's no job it will look for more jobs when the timeout happens again after a second:  `{ :noreply, state, @default_timeout }`

If some job finishes, the timeout happens "instantly" (after 0 ms) ` { :noreply, state, 0 }` You can see this when WorkersManager receives a `:done` or some `DOWN` message from the monitor.

**Comment by railsmechanic** [comment]
Thank you for explaining that to a noob...:+1::smile:

**Comment by edgurgel** [comment]
Great! Do you mind if I close the issue? :)

**Comment by railsmechanic** [comment]
No, please close it...
