### ISSUE TITLE
s/GenEvent/GenStage/g

### ISSUE THREAD

**Issue by edgurgel** [edgurgel/verk#100]
We should probably do this in a way that we would have both running at the same time while users can move their handlers (if any) to the new architecture.

Why? `GenEvent` has lots of issues that we want to avoid. More info here: http://elixir-lang.org/blog/2016/07/14/announcing-genstage/

**Comment by mitchellhenke** [comment]
I'll hopefully have a go at this soon 🙂

**Comment by edgurgel** [comment]
Awesome :)

**Comment by teamon** [comment]
+100, GenEvent handles like to break a lot in development when recompiling.
Although I'm not sure if GenStage is really needed (this would be one more additional dependency to track versions/changes)

**Comment by mitchellhenke** [comment]
@teamon is there something else to use instead of GenStage? While it's not 1.0 quite yet, it has at least been dropped from the "Experimental" namespace 🙂

**Comment by teamon** [comment]
Don't get me wrong, I am a big fan of GenStage, I just wonder if it is really needed. I guess it's worth to mention that I'm only talking about using GenEvent for monitoring, not the internals. If GenEvent is used for the job processing it definitely might be a good idea to use GenStage :)
