### ISSUE TITLE
Retry now from web ui

### ISSUE THREAD

**Issue by teamon** [edgurgel/verk#107]
I think the option to "retry now" selected failed jobs would be useful - i.e. to run failed jobs after deploying a fixed codebase.

Thoughts?

**Comment by edgurgel** [comment]
Yes we have plans to add it: https://github.com/edgurgel/verk_web/issues/11

**Comment by teamon** [comment]
Ahh, sorry, I haven't checked that repo. Keep up the good work!

**Comment by edgurgel** [comment]
All good! Thanks! 👍
