### ISSUE TITLE
Task :timeout

### ISSUE THREAD

**Issue by taorg** [edgurgel/verk#111]
Hello, how can we configure Verk task (worker) timeout?
We have an applications with several taks, all of then works fine, but some file transfers, take more than tak timeouts and always fail.

How should we configure it ?
We've tryed with workers_manager_timeout: 360000 but we still got  timeout

```
[debug] Worker got down, reason: :timeout, [#Reference<0.0.6.1826>, #PID<0.760.0>]
[debug] Rumbl.VideoWorker 20668957681470793693 fail: 31 s
[error] Task #PID<0.782.0> started from #PID<0.760.0> terminating
** (stop) exited in: Task.Supervised.stream(30000)
```
Thanx

**Comment by edgurgel** [comment]
Hey @taorg, Verk does not use Task anywhere. This is probably coming from the lib you are using. There's no timeout for Verk workers. They can take as much time as you want.

**Comment by taorg** [comment]
Hello @edgurgel, thank you very much for your reply, it helps a lot.
Thx
