### ISSUE TITLE
Jobs with high priority (gap)

### ISSUE THREAD

**Issue by salisbury-espinosa** [edgurgel/verk#118]
Is it possible to do so that until tasks from the highest priority queue are completed, do not start tasks from others. Or set the task at the top of the queue so that it runs in high priority - RPUSH insteadof LPUSH in Verk.enqueue

**Comment by edgurgel** [comment]
A possible solution is to have 2 queues:

* low-priority
* high-priority 

And the amount of workers for the high-priority is greater than the low-priority. This way the high-priority queue will be processed faster than the low-priority and the low-priority will still slowly progress. Would this suffice your use case?

**Comment by salisbury-espinosa** [comment]
I saw this example in the documentation, but the tasks will not be processed in priority order in this case
for example,  implementation of the `perform` method of all workers contains `GenServer.call` to the same pid
