### ISSUE TITLE
Questions around failure handling

### ISSUE THREAD

**Issue by lpil** [edgurgel/verk#122]
Hello!

I've just discovered this library, and I'm interested in how it compares to https://github.com/akira/exq

There were a few things I was unable to determine from the documentation and a very quick scan of the codebase.

- Is there a limit to how long a worker can take to process a job?
- When a node goes down and does not recover, how is it determined which "in process" jobs need to be requeued, and how does the failure detection mechanism work?

It'd be great if the algorithm was documented so it's easier to make an informed decision when evaluating worker libs :)

Thanks,
Louis

**Comment by edgurgel** [comment]
Hi @lpil, I will reply to these questions ASAP. Hopefully we can add this to a wiki page or to the README.md :)

**Comment by lpil** [comment]
Fab, thank you. :)

**Comment by edgurgel** [comment]
> * Is there a limit to how long a worker can take to process a job?

No. There's no limit.

> * When a node goes down and does not recover, how is it determined which "in process" jobs need to be requeued, and how does the failure detection mechanism work?

Verk will save a list of `inprogress` jobs using a node id that you can define as part of your runtime configuration. When Verk restarts it will pick them up and move them back to the top of the queue to run again.  Each node must have a different id.

**Comment by lpil** [comment]
Seems to be the same as Exq then. If a node goes down and does not recover those jobs are lost without human intervention. Same for if you cluster scales down and a worker is shut down before completing.

I'm surprised I didn't know about the node id configuration, seems very important. Maybe I missed that bits of the docs?

**Comment by edgurgel** [comment]
Yeah, it's barely mentioned here: https://github.com/edgurgel/verk#configuration

Yeah scaling a cluster of Verk instances can be tricky currently. And we can't guarantee that a Verk instance will have time to move the `inprogress` list back to the queues before it goes down. 

The actual problem currently it's that Verk instances do not know about other instances so they can't coordinate any sort of work currently. Once we solve this bit we can then for example ask for a different node to take care of the nodes that are not up anymore and requeue the `inprogress` lists.

**Comment by lpil** [comment]
Great, thank you for your help :)

**Comment by edgurgel** [comment]
I think we now have a great section about this topic : https://github.com/edgurgel/verk#deployment
