### ISSUE TITLE
Association values are empty inside worker

### ISSUE THREAD

**Issue by kirqe** [edgurgel/verk#124]
Hi, Here're a few parts of my code from a controller

`campaign = Repo.get!(Campaign, id) |> Repo.preload(group: :users)`

`Verk.enqueue(%Verk.Job{queue: :default, class: "EmailWorker", args: [campaign], max_retry_count: 5})`

And here's what I get inside worker when inspecting campaign `args\":[{\"group\":{},\"`

Group **values** are available inside controller but **empty inside worker**.

I also added 
  `@derive {Poison.Encoder, only: [:name, :subject, :body, :group]} ` to Campaign model
  `@derive {Poison.Encoder, only: [:user]}` to User model

Any advise, please? 
Thanks

**Comment by edgurgel** [comment]
@kirqe , did you find what was the problem?

**Comment by kirqe** [comment]
Yes, thanks. It started working after I restarted the server. I also needed to add `:users` to Group's  encoder. `@derive {Poison.Encoder, only: [:name, :users]}`

Sorry for opening the issue.

**Comment by edgurgel** [comment]
All good! 👍
