### ISSUE TITLE
Wrong elixir requirement?

### ISSUE THREAD

**Issue by teamon** [edgurgel/verk#136]
When compiling with elixir 1.3

```
==> confex
warning: the dependency :confex requires Elixir "~> 1.4" but you are running on v1.3.4
Compiling 6 files (.ex)
```

If this mean confex won't run correctly on elixir 1.3 I think verk should also have `~> 1.4` as a requirement.

**Comment by edgurgel** [comment]
Oh yeah you are right! 😶

**Comment by edgurgel** [comment]
1.0.2 is out with the proper requirement. Thanks for the bug report! 👍
