### ISSUE TITLE
Elixir 1.6 compat with warnings as errors

### ISSUE THREAD

**Issue by halfdan** [edgurgel/verk#147]
We use warnings as errors and `verk` shows up as one of the packages that produces a number of warnings on Elixir 1.6.

```
==> verk
Compiling 23 files (.ex)
warning: module attribute @lint was set but never used
  lib/verk/queue_manager.ex:93

Generated verk app
```

I'm not sure what the right thing to do here is, but I'm happy to create a PR if someone can point me in the right direction.

**Comment by edgurgel** [comment]
Yeah that's interesting. The lint attribute is used by credo. So if credo is not running this attribute will be ignored... 🤔  I think this issue has the way to go: https://github.com/rrrene/credo/issues/291

So I think this needs to be done: https://github.com/rrrene/credo#inline-configuration-via-config-comments
