### ISSUE TITLE
Failed jobs (argument error) retrying indefinitely with max retry count..

### ISSUE THREAD

**Issue by damien-roche** [edgurgel/verk#151]
I'm not sure how best to debug this.

In development, I accidentally queued a job with bad arguments. This appears to result in an infinite crash loop where it crashes the worker manager, then queue manager kicks and starts it up again, the job is then retried, and the same exception crashes the worker manager ad infinitum.

Not sure why the retry limit is not kicking in. Checking redis, it doesn't look like the job ever gets out of the inprogress queue. The only way I've been able to not have this blow up when restarting the worker process is to remove the offending job.

Here is a typical loop:

```
[info] Workers Manager started for queue default (running)
[info] Added 1 jobs.
[info] No more jobs to be added to the queue default from inprogress list.
[info] Pingerly.CheckWorker 31778725081843328696 start
[debug] Job failed reason: %ArgumentError{message: "argument error"}
[info] Pingerly.CheckWorker 31778725081843328696 fail: 0 ms
[error] GenServer #PID<0.2274.0> terminating
** (stop) :failed
Last message: {:"$gen_cast", {:perform, %Verk.Job{args: [1], class: "Pingerly.CheckWorker", enqueued_at: 1519110069, error_backtrace: nil, error_message: nil, failed_at: nil, finished_at: nil, jid: "31778725081843328696", max_retry_count: 3, original_json: "{\"retry_count\":0,\"retried_at\":null,\"queue\":\"default\",\"max_retry_count\":3,\"jid\":\"31778725081843328696\",\"finished_at\":null,\"failed_at\":null,\"error_message\":null,\"error_backtrace\":null,\"enqueued_at\":1519110069,\"class\":\"Pingerly.CheckWorker\",\"args\":[1]}", queue: "default", retried_at: nil, retry_count: 0}, #PID<0.2275.0>}}
State: nil
[error] Manager terminating, reason: {{:badarg, [{:erlang, :binary_to_existing_atom, ["Elixir.Pingerly.CheckWorker", :utf8], []}, {:elixir_aliases, :safe_concat, 1, [file: 'src/elixir_aliases.erl', line: 119]}, {Verk.RetrySet, :calculate_retry_at, 3, [file: 'lib/verk/retry_set.ex', line: 38]}, {Verk.RetrySet, :add, 3, [file: 'lib/verk/retry_set.ex', line: 20]}, {Verk.RetrySet, :add!, 3, [file: 'lib/verk/retry_set.ex', line: 34]}, {Verk.QueueManager, :handle_call, 3, [file: 'lib/verk/queue_manager.ex', line: 132]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 636]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 665]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, {GenServer, :call, [:"default.queue_manager", {:retry, %Verk.Job{args: [1], class: "Pingerly.CheckWorker", enqueued_at: 1519110069, error_backtrace: nil, error_message: nil, failed_at: nil, finished_at: nil, jid: "31778725081843328696", max_retry_count: 3, original_json: "{\"retry_count\":0,\"retried_at\":null,\"queue\":\"default\",\"max_retry_count\":3,\"jid\":\"31778725081843328696\",\"finished_at\":null,\"failed_at\":null,\"error_message\":null,\"error_backtrace\":null,\"enqueued_at\":1519110069,\"class\":\"Pingerly.CheckWorker\",\"args\":[1]}", queue: "default", retried_at: nil, retry_count: 0}, 1519110071, %ArgumentError{message: "argument error"}, [{:erlang, :binary_to_existing_atom, ["Elixir.Pingerly.CheckWorker", :utf8], []}, {:elixir_aliases, :safe_concat, 1, [file: 'src/elixir_aliases.erl', line: 119]}, {Verk.Worker, :handle_cast, 2, [file: 'lib/verk/worker.ex', line: 35]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, 5000]}}

[info] Queue Manager started for queue priority

```
wrapped:

> [info] Workers Manager started for queue default (running)
> [info] Added 1 jobs.
> [info] No more jobs to be added to the queue default from inprogress list.
> [info] Pingerly.CheckWorker 31778725081843328696 start
> [debug] Job failed reason: %ArgumentError{message: "argument error"}
> [info] Pingerly.CheckWorker 31778725081843328696 fail: 0 ms
> [error] GenServer #PID<0.2274.0> terminating
> ** (stop) :failed
> Last message: {:"$gen_cast", {:perform, %Verk.Job{args: [1], class: "Pingerly.CheckWorker", enqueued_at: 1519110069, error_backtrace: nil, error_message: nil, failed_at: nil, finished_at: nil, jid: "31778725081843328696", max_retry_count: 3, original_json: "{\"retry_count\":0,\"retried_at\":null,\"queue\":\"default\",\"max_retry_count\":3,\"jid\":\"31778725081843328696\",\"finished_at\":null,\"failed_at\":null,\"error_message\":null,\"error_backtrace\":null,\"enqueued_at\":1519110069,\"class\":\"Pingerly.CheckWorker\",\"args\":[1]}", queue: "default", retried_at: nil, retry_count: 0}, #PID<0.2275.0>}}
> State: nil
> [error] Manager terminating, reason: {{:badarg, [{:erlang, :binary_to_existing_atom, ["Elixir.Pingerly.CheckWorker", :utf8], []}, {:elixir_aliases, :safe_concat, 1, [file: 'src/elixir_aliases.erl', line: 119]}, {Verk.RetrySet, :calculate_retry_at, 3, [file: 'lib/verk/retry_set.ex', line: 38]}, {Verk.RetrySet, :add, 3, [file: 'lib/verk/retry_set.ex', line: 20]}, {Verk.RetrySet, :add!, 3, [file: 'lib/verk/retry_set.ex', line: 34]}, {Verk.QueueManager, :handle_call, 3, [file: 'lib/verk/queue_manager.ex', line: 132]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 636]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 665]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, {GenServer, :call, [:"default.queue_manager", {:retry, %Verk.Job{args: [1], class: "Pingerly.CheckWorker", enqueued_at: 1519110069, error_backtrace: nil, error_message: nil, failed_at: nil, finished_at: nil, jid: "31778725081843328696", max_retry_count: 3, original_json: "{\"retry_count\":0,\"retried_at\":null,\"queue\":\"default\",\"max_retry_count\":3,\"jid\":\"31778725081843328696\",\"finished_at\":null,\"failed_at\":null,\"error_message\":null,\"error_backtrace\":null,\"enqueued_at\":1519110069,\"class\":\"Pingerly.CheckWorker\",\"args\":[1]}", queue: "default", retried_at: nil, retry_count: 0}, 1519110071, %ArgumentError{message: "argument error"}, [{:erlang, :binary_to_existing_atom, ["Elixir.Pingerly.CheckWorker", :utf8], []}, {:elixir_aliases, :safe_concat, 1, [file: 'src/elixir_aliases.erl', line: 119]}, {Verk.Worker, :handle_cast, 2, [file: 'lib/verk/worker.ex', line: 35]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}, 5000]}}
> 
> [info] Queue Manager started for queue priority

**Comment by edgurgel** [comment]
Thanks for the bug report! I will take a look as soon as possible. I think I know what's the issue. We can definitely avoid this issue.

**Comment by damien-roche** [comment]
Very cool! Thanks very much. I'd dive in myself, but I'm only a week into Elixir.

**Comment by lms-lamhuynh** [comment]
I mis-typed worker name and now the whole server won't start until I do `redis-cli flushall`. There must be a better way of handling errors like this

**Comment by damien-roche** [comment]
Glad to see I'm not the only one who ran into this. It wouldn't be so much of a problem if you passed the worker module constants around - but the fact it is passed in as a string removes all compile-time checks that would at least catch this issue before it blows up everything else.

I think there just needs to be a simple check for constant before attempting to call `perform`, etc

**Comment by edgurgel** [comment]
yeah I agree @damien-roche we should definitely cleanly fail like we do for other common errors. As soon as I have some time to work on Verk I will fix this. 👍

**Comment by edgurgel** [comment]
Related to https://github.com/edgurgel/verk/pull/141
