### ISSUE TITLE
Question. Can Verk check more frequently for new jobs?

### ISSUE THREAD

**Issue by florinpatrascu** [edgurgel/verk#173]
Hi there - I have a system using Verk and I am curious if Verk can check for new jobs more frequently (with Redis)? If yes, is that a configuration setting I could use? Thank you!

**Comment by edgurgel** [comment]
Yes. There's a `workers_manager_timeout` which is not the best name I've ever created 🤔 

We use this number (in milliseconds) + some randomness to fetch new jobs from Redis.

**Comment by florinpatrascu** [comment]
Awesome! Thank you!!
