### ISSUE TITLE
function Verk.Supervisor.start_link/1 is undefined or private

### ISSUE THREAD

**Issue by robinvdvleuten** [edgurgel/verk#179]
I am trying to add Verk to my supervised processes in a Phoenix 1.4 application;

```elixir
children = [
      MyApp.Repo,
      MyAppWeb.Endpoint,
      Verk.Supervisor
]
```

But whenever I start my application, I receive the following error;

```
** (Mix) Could not start application submit: MyApp.Application.start(:normal, []) returned an error: shutdown: failed to start child: Verk.Supervisor
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function Verk.Supervisor.start_link/1 is undefined or private
```

**Comment by edgurgel** [comment]
Could you please check which version of Verk is defined inside your `mix.lock`? It should be defined if it's loaded 🤔

**Comment by edgurgel** [comment]
Fixed by https://github.com/edgurgel/verk/commit/51250f78f01d1803a7263e93de7c483a1d1d3579
