### ISSUE TITLE
Coupling of producers and consumers?

### ISSUE THREAD

**Issue by ilgarm** [edgurgel/verk#187]
Hello,

Maybe I am getting something wrong here, please correct. Doesn't the requirement of having a worker class defined at the moment of enqueuing couples producers and consumers?

Consider the case when I have two different codebases relevant to separate clusters, and I want to set up a communication channel between them. So, the producer has to know the queue name and in addition a module name on the consuming application? Is that correct? If so, why it was designed that way and not having a mapping of queues and workers on the consumer side?

Thanks.

**Comment by edgurgel** [comment]
Verk works with specific type of jobs. It was not meant to be used like a topic of data (like Kafka, Rabbitmq). There's no concept of consumers or producers anywhere.
