### ISSUE TITLE
Upgrade GenStage to current version

### ISSUE THREAD

**Issue by youalreadydid** [edgurgel/verk#188]
Hi,

I'm using Verk in an application, but now I need to consume some RabbitMQ messages and decided to try the [Broadway](https://github.com/plataformatec/broadway) library. The problem is that Verk set GenStage at 0.12 version, while Broadway set it at 0.14 (current), so I can't use them together :(

Is possible to upgrade this dependency? Thanks!

**Comment by edgurgel** [comment]
Yes! Definitely! We can relax the dependency to `0.14` (currently 0.12.1) and it will accept everything but `1.0` (so if 0.15 comes out it will already be accepted)

**Comment by joskar** [comment]
@edgurgel What is the state of this? Is someone working on this? I might have time to do so.

**Comment by edgurgel** [comment]
Hey @joskar, we still need to do this. Because master is preparing for 2.0 release I will do this myself releasing a new tag on the 1.* series 👍 Thanks for bringing this up. It should be out before Christmas 😆 🎄

**Comment by joskar** [comment]
Hey @edgurgel, I'm really happy to hear that!  
Thank you for taking the time to reply :)

**Comment by edgurgel** [comment]
1.6.4 is out 🎉 I think this fixes this issue 👍
