### ISSUE TITLE
Utilize Redis Connection Outside Verk

### ISSUE THREAD

**Issue by veverkap** [edgurgel/verk#23]
I'm fairly new to Elixir so there might be an obvious answer to this, but is there an easy way to reuse the Redix connection that Verk opens up elsewhere in the code?

**Comment by edgurgel** [comment]
Yes! You can simply use `Verk.Redis` as the process that you want to interact with. 

Something like [this](https://github.com/edgurgel/verk/blob/aff780a7176653a01e381e9e28a81047e3bc230a/lib/verk/queue.ex#L12)

`Redix.command!(Verk.Redis, ["LLEN", queue_name(queue)])`

**Comment by veverkap** [comment]
AWESOME!  Thanks!

Really liking Verk a lot.

**Comment by edgurgel** [comment]
:+1: :tada:

**Comment by veverkap** [comment]
@edgurgel is there any way to adjust the connection pool size?

**Comment by edgurgel** [comment]
There's no pool of connections. Verk has 1 general usage connection (`Verk.Redis`), 1 connection for the ScheduleManager and 1 connection per QueueManager(which means 1 connection per queue).

What can be done is a simple function to start a new one if some user needs. Maybe adding a new function like

`Verk.Redis.start_link/0`

This would start a new redis connection using the same configuration that Verk is configured to use. Which would simply be using `Application.get_env(:verk, :redis_url)` as argument to `Redix.start_link/1`

What do you think?
