### ISSUE TITLE
Handle case where Redis is down then up

### ISSUE THREAD

**Issue by akira** [edgurgel/verk#4]
I was playing with this, and saw an issue if we disconnect Redis and then reconnect it. 

Once Redis is back up, I'm getting this error:
```
Failed to fetch retry set. Error: {:error, %Redix.Error{message: "NOSCRIPT No matching script. Please use EVAL."}}
```
Looks like the Lua scripts need to be reloaded?  Wonder if there is a way to listen to disconnect/reconnect events from Redix.

**Comment by edgurgel** [comment]
Yeah restarting Redis will flush the instance which is different from losing connection with Redis. I don't even know how to properly check if the script is good to be used at this point. Nice catch! Thanks for the report!

**Comment by edgurgel** [comment]
Apparently the way to go is to always send an INFO command when a connection is set up and check if the `run_id` didn't change. 

It's easy to keep the `run_id` on an ETS table and just check if the value is the same. If it's not, reload them. 
From Redis docs


> Also, as already mentioned, restarting a Redis instance flushes the script cache, which is not persistent. However from the point of view of the client there are only two ways to make sure a Redis instance was not restarted between two different commands.

>    The connection we have with the server is persistent and was never closed so far.
>    The client explicitly checks the runid field in the INFO command in order to make sure the server was not restarted and is still the same process.

http://redis.io/commands/EVAL

**Comment by edgurgel** [comment]
Other safe way is to always load the scripts when a connection is set up ¯\_(ツ)_/¯

**Comment by whatyouhide** [comment]
@edgurgel I'm working on a "resiliency API" that will let you hook functions up for disconnections/failed connections events, but right now yeah, it'll blindly try to reconnect :\ I'll let you know when the new API is ready!

**Comment by edgurgel** [comment]
Cool! Thanks for the heads up :)
