### ISSUE TITLE
Timex Version

### ISSUE THREAD

**Issue by veverkap** [edgurgel/verk#40]
What would be the impact of upgrading to Timex 2.0?

**Comment by edgurgel** [comment]
Probably none! It should be pretty straightforward to upgrade. Want to send a PR? I can do myself later this week.

**Comment by krasio** [comment]
#43.

**Comment by edgurgel** [comment]
Closed by https://github.com/edgurgel/verk/pull/43. I will release a new version soon!

**Comment by krasio** [comment]
I missed some migration steps, see #46 for details.
