### ISSUE TITLE
Change Verk.Queue, Verk.RetrySet, Verk.SortedSet to have clear!/clear, range!/range...

### ISSUE THREAD

**Issue by edgurgel** [edgurgel/verk#49]
These modules should offer "twins" of each function:

Example: `clear!` and `clear` where `clear` returns` {:ok, something}` or `{:error, reason}` and `clear!` will return `something` or throw an error. 

This should be done soon as we don't want to break this API after we release 1.0.0

**Comment by krasio** [comment]
Do you mean something simple like

```elixir
  def count(queue) do
    Redix.command(Verk.Redis, ["LLEN", queue_name(queue)])
  end  

  def count!(queue) do
    case count(queue) do
      {:ok, resp} ->
        resp 
      {:error, error} ->
        raise error
    end  
  end
```
or something a little bit more elaborate like returning/raising `Verk.Error` instead of raw `Redix.Error`, etc...

**Comment by edgurgel** [comment]
It could be simple like that. We could even use a macro like this PR: https://github.com/ericmj/mongodb/pull/51/files the `bangify!`

**Comment by krasio** [comment]
Can you please take a look and check am I on the right track - https://github.com/krasio/verk/commits/issues/49.

**Comment by edgurgel** [comment]
@krasio, that's exactly what I had in mind. Thank you very much! :heart:
