### ISSUE TITLE
Investigate how to format the stacktrace when it is not a list

### ISSUE THREAD

**Issue by edgurgel** [edgurgel/verk#64]
Related to https://github.com/edgurgel/verk/pull/61

I think we should investigate what's the right approach here. Maybe checking ExUnit's code on how they treat this case.

**Comment by krasio** [comment]
Looks like this may be bug in `System.stacktrace`:

> josevalim
> Can you provide a way to reproduce this? I would expect System.stacktrace to always return a list. If it does not, it is surely a bug

https://elixirforum.com/t/system-stacktrace-returning-a-genserver-call-tuple/513

**Comment by edgurgel** [comment]
@krasio awesome finding! 💃

**Comment by edgurgel** [comment]
We already have code to catch this possible error, but we have no easy way to replicate. I will close for now 👍
