### ISSUE TITLE
Why not mnesia/dets

### ISSUE THREAD

**Issue by imranismail** [edgurgel/verk#68]
I've just started Elixir, and I just wonder what was your reasoning against using an erlang built in solution like Mnesia or DETS for this instead of Redis?

I hope that doesn't sound harsh or offend you, this is a great library. 

I just want to get some answers as it's been on my head for quite a bit.

**Comment by edgurgel** [comment]
Don't worry you offend me by asking a question :P 

I wrote a bit about why I picked Redis over Mnesia: https://news.ycombinator.com/item?id=11256867

> That's a great question. I chose Redis for 2 reasons:
> * Simple to use
> * Compatibility with other systems like Sidekiq/Resque. Out of the box it will understand their clients.

> My experience with Mnesia is close to none but I know it's not trivial to deal with split brain scenarios for example. It's also complicated to connect multiple nodes for my use case (using docker) and also to deal with moving instances inside a cluster. I would need to care about the locality of the data.

> One can use any Redis service (AWS Elasticache, Redis Labs) and not care about maintaining a database. The Verk user just needs to have a working Redis database. Then spinning new Verk instances pointing to the same database would naturally increase the throughput without any synchronization or data exchange through the Verk nodes.

> I'm pretty sure that having the database in the same space as the job processing system would speed up things. I would love to see a project that tried this approach. Probably not using JSON but simply Erlang terms.

**Comment by imranismail** [comment]
Haha, I did huh? Anyways, that seems very reasonable! AWS Elasticache is awesome. Thanks for answering!
