### ISSUE TITLE
How to get current jobs queued up in all queues?

### ISSUE THREAD

**Issue by sergiotapia** [edgurgel/verk#77]
I have a few jobs that spawn a very large number of child jobs. 

I want to run these initial "spawning" jobs only when the queues are at 0. How can I check that?

**Comment by edgurgel** [comment]
You can use `Verk.Queue.count` https://github.com/edgurgel/verk/blob/master/lib/verk/queue.ex but I don't know if it will be super efficient as you need to keep checking for the count?

You could also investigate using a handler: https://github.com/edgurgel/verk#error-tracking

**Comment by edgurgel** [comment]
I'm closing but feel free to reopen if it was not enough information
