### ISSUE TITLE
Timex 3 support

### ISSUE THREAD

**Issue by karmajunkie** [edgurgel/verk#78]
Timex 3 is the latest major version, so Verk should probably support that. Opening this ticket to track that support.

**Comment by mitchellhenke** [comment]
Would dropping Timex in favor of standard Elixir/Erlang times be something to consider if it's a breaking change anyway?

**Comment by karmajunkie** [comment]
I think its worth considering, though its not just a matter of the date/time structs, which AFAIK is primarily what elixir standardized in 1.3. Timex also adds niceties for dealing with things like durations and timezones that can still be a PITA with the stock functions.  That said, I think the primary use of datetimes in Verk is to mark when jobs were enqueued and whether enough time has passed, which can probably done with the standard library functions.

**Comment by karmajunkie** [comment]
Reviewing the usages of Timex, the _primary_ utility is to get the current unix time, which can easily be replaced by standard lib. There are a couple of ancilliary uses of `Timex.shift` and `Timex.compare` which _could_ be abstracted away if maintainers feel like dropping the dependency is worthwhile. My 2 cents is to be generally in favor of killing dependencies when the utility of them is shallow, as I think it is in this case.

**Comment by edgurgel** [comment]
Thanks @mitchellhenke and @karmajunkie. I would be keen to move to `~> 1.3` and remove Timex from our dependencies. What do you folks think?

@karmajunkie, would you be interested in creating a PR? I can definitely work on this till the end of the week (2-3 days from now). 

Seems legit?

Then I will just need to update Verk Web to either work with Timex 3 or use standard Elixir :)

**Comment by edgurgel** [comment]
Not part of this work but I will also use this moment to move to Poison 2 and remove this code https://github.com/edgurgel/verk/blob/master/lib/verk/poison_version.ex

**Comment by karmajunkie** [comment]
@edgurgel i've got it mostly done now, but having a hard time figuring out how to get `meck` to work. Its not a library I've used before, and in general I try to avoid that kind of mocking so not sure what needs to change to get those tests passing. I'm sure I've made worse whatever my original testing issue was, but maybe you can take a look at it and see. I'll try to get the work I did today to remove Timex pushed up tonight or tomorrow morning on #79.

**Comment by mitchellhenke** [comment]
That sounds super to me

**Comment by edgurgel** [comment]
Cool I will take a look at this today! Thank you again for starting this :)

**Comment by karmajunkie** [comment]
Closing this as #79 was merged in, resolving the issue

**Comment by edgurgel** [comment]
Awesome! I will update Poison and others libs then release a new major version! Thanks again :)

**Comment by edgurgel** [comment]
Verk 0.13.0 is out https://github.com/edgurgel/verk/releases/tag/v0.13.0 https://hex.pm/packages/verk/0.13.0 
Thanks!
