### ISSUE TITLE
Configurable max retries

### ISSUE THREAD

**Issue by mitchellhenke** [edgurgel/verk#81]
For myself, the use case is not wanting to retry certain types of jobs, and some others I'd like to retry less than the default.

I would be willing add the feature if this is something would be beneficial to have in Verk.

**Comment by edgurgel** [comment]
Yes, I want this feature 👍 

Do you have any idea on how to approach? I can spend some time architecting the implementation details

**Comment by mitchellhenke** [comment]
@edgurgel I'm not sure.  My initial thought was something like `use Verk.Job` with a `defoverridable` max_retry_count function.

**Comment by edgurgel** [comment]
What would be the most generic way to support this? 

What I was thinking was: add a `:max_retries` key and each job can have a different `max_retries`. 

And then use this OR the "global" definition (which could be an Application env also)

What do you reckon?

**Comment by mitchellhenke** [comment]
My use case is that I have a number of different kinds of jobs with a varying amount of times each may be run.  I think being able to set it globally, per job type, and per individual job makes sense, and I like the idea of moving it into the Job module/struct.  I'm not sure I like requiring it be specified each time, though being able to configure it per job type is probably the most complex option to add.

I'll take a shot at adding global config through application env, and allowing the client to provide on a per job basis, and see how things go.

**Comment by edgurgel** [comment]
Awesome! And we can probably kinda of do all the things proposed above...

Thanks for starting this work!
