### ISSUE TITLE
Error Retries and Exponential Backoff

### ISSUE THREAD

**Issue by tlvenn** [edgurgel/verk#83]
Hi,

It is not very apparent looking at the doc if the retry mechanism implements any kind of exponential backoff. If not, I believe it would be a good addition. Thanks

**Comment by edgurgel** [comment]
Sorry! Somehow I missed your issue! We already have a kind of backoff:

https://github.com/edgurgel/verk/blob/master/lib/verk/retry_set.ex#L37-L40

We definitely should document the "average" (as it has a random component) difference between the retries and maybe the "average" last retry.

**Comment by tlvenn** [comment]
Hey no worry, thanks for getting back to me and great to hear it's implemented already. I think it would suffice to edit the Feature Set first item to say `Retry mechanism with exponential backoff`
